-- 코드를 작성해주세요
SELECT
    II.ITEM_ID,
    II.ITEM_NAME,
    II.RARITY
FROM
    ITEM_TREE AS IT
RIGHT JOIN
    ITEM_INFO AS II
ON
    IT.PARENT_ITEM_ID = II.ITEM_ID
WHERE
    IT.PARENT_ITEM_ID IS NULL
ORDER BY
    II.ITEM_ID DESC
;