SELECT
    ugu.USER_ID,
    ugu.NICKNAME,
    SUM(ugb.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD ugb
JOIN
    USED_GOODS_USER ugu
ON
    ugb.WRITER_ID = ugu.USER_ID
WHERE
    ugb.STATUS = 'DONE'
GROUP BY
    ugu.USER_ID, ugu.NICKNAME
HAVING
    SUM(ugb.PRICE) >= 700000
ORDER BY
    TOTAL_SALES ASC
;